### ISSUE TITLE
请问有做好的实例代码嘛？

### ISSUE THREAD

**Issue by lianshuang** [Grand-cocoa/print-designer#1]

**Comment by Grand-cocoa** [comment]
您好，本仓库是目前为内部使用而建立并基于 myliuxia/kr-print-designer 做了些许修改以更适合使用场景，暂不提供实例代码，后续将更新 README.md 文件提供接口，若有需要请前往[myliuxia/kr-print-designer](https://www.github.com/myliuxia/kr-print-designer)查看具体使用示例，本仓库 README.md 中的示例亦指向原仓库[示例](https://myliuxia.github.io/demo/kr-print-designer/index.html)
